### ISSUE TITLE
Provide a configuration script

### ISSUE THREAD

**Issue by kewashi** [kewashi/HousePanel#6]
Write an install PHP script that will write the clientinfo.php file as well as handle other configuration settings such as checking for Curl availability and picking an options persistence method - DB, File, or Session. Session will be the simplest but least persistent. Then again with the Sessions approach one can have different configurations on different devices. Hmmmm I think I can implement that too with the other options

**Comment by carloslebreiro** [comment]
Could you please also move the timezone definition (line 44 of housepanel.php) into the clientinfo.php?

**Comment by kewashi** [comment]
Actually I can get the time zone from the API
		

		________________________________
Ken Washington
ken@kenw.com
	





On Sun, Jul 16, 2017 at 2:56 AM -0400, "Carlos Lebreiro" <notifications@github.com> wrote:












Could you please also move the timezone definition (line 44 of housepanel.php) into the clientinfo.php?

**Comment by kewashi** [comment]
Closing this old issue and will open a new one specifically tied to need for improved updated install help
